version: "3"
services:
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    container_name: zookeeper_cont
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      
  kafka:
    image: 'bitnami/kafka:latest'
    container_name: kafka_cont
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1      
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:2181
      ALLOW_PLAINTEXT_LISTENER: "yes"
    depends_on:
      - zookeeper

  db:
    image: postgres:latest
    container_name: db_cont
    environment:
      - POSTGRES_USER=narendra
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=practice
      - DATABASE_HOST=db
    ports:
      - '5432:5432'
    volumes:
      - database_postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: narendra@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    depends_on:
      - db
    ports:
      - "5050:80"
    restart: unless-stopped
volumes:
  database_postgres: